CREATE DATABASE CLINICA_VETERINARIA;

USE CLINICA_VETERINARIA;

CREATE TABLE TIPO_ANIMAIS(
	TIPO_ANIMAL VARCHAR(255)    
);


CREATE TABLE ANIMAIS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    ID_TIPO_ANIMAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_NASCIMENTO DATETIME NOT NULL,
    COR VARCHAR (20),
    PESO FLOAT NOT NULL,
    ALTURA FLOAT NOT NULL
);