CREATE VIEW VW_SESSAO_DETALHADA AS
SELECT
    S.ID_SESSAO,
    S.HORARIO_INICIO,
    S.HORARIO_TERMINO,
    S.VALOR_INGRESSO,
    S.IDIOMA_EXIBICAO,
    S.TIPO_EXIBICAO,
    S.STATUS_SESSAO,
    F.TITULO AS TITULO_FILME,
    F.DURACAO_MINUTOS,
    F.CLASSIFICACAO_INDICATIVA,
    SA.NUMERO_SALA,
    SA.CAPACIDADE AS CAPACIDADE_SALA,
    C.NOME_FANTASIA_CINEMA AS NOME_CINEMA,
    C.ENDERECO_CINEMA AS ENDERECO_CINEMA
FROM
    SESSAO S
JOIN
    FILME F ON S.ID_FILME = F.ID_FILME
JOIN
    SALA SA ON S.ID_SALA = SA.ID_SALA
JOIN
    CINEMA C ON SA.ID_CINEMA = C.ID_CINEMA;

CREATE VIEW VW_OCUPACAO_SALA_POR_CINEMA AS
SELECT
    C.NOME_FANTASIA_CINEMA AS NOME_CINEMA,
    SA.NUMERO_SALA,
    SA.CAPACIDADE AS CAPACIDADE_SALA,
    S.ID_SESSAO,
    F.TITULO AS TITULO_FILME,
    S.HORARIO_INICIO,
    S.HORARIO_TERMINO,
    FN_CALCULAR_TOTAL_INGRESSOS_SESSAO(S.ID_SESSAO) AS INGRESSOS_VENDIDOS_RESERVADOS,
    (SA.CAPACIDADE - FN_CALCULAR_TOTAL_INGRESSOS_SESSAO(S.ID_SESSAO)) AS LUGARES_DISPONIVEIS
FROM
    CINEMA C
JOIN
    SALA SA ON C.ID_CINEMA = SA.ID_CINEMA
JOIN
    SESSAO S ON SA.ID_SALA = S.ID_SALA
JOIN
    FILME F ON S.ID_FILME = F.ID_FILME; 