DELIMITER //

CREATE FUNCTION FN_CALCULAR_TOTAL_INGRESSOS_SESSAO(P_ID_SESSAO INT)
RETURNS INT
READS SQL DATA
BEGIN
    DECLARE V_TOTAL_INGRESSOS INT;

    SELECT COUNT(ID_INGRESSO)
    INTO V_TOTAL_INGRESSOS
    FROM INGRESSO
    WHERE ID_SESSAO = P_ID_SESSAO
    AND STATUS_INGRESSO IN ('VENDIDO', 'RESERVADO');

    RETURN V_TOTAL_INGRESSOS;
END;
//

CREATE FUNCTION FN_OBTER_LISTA_FILMES_ATOR(P_ID_ATOR INT)
RETURNS TEXT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
READS SQL DATA
BEGIN
    DECLARE V_LISTA_FILMES TEXT DEFAULT '';

    SELECT GROUP_CONCAT(F.TITULO SEPARATOR ', ')
    INTO V_LISTA_FILMES
    FROM FILME F
    JOIN FILME_ATOR FA ON F.ID_FILME = FA.ID_FILME
    WHERE FA.ID_ATOR = P_ID_ATOR;

    RETURN V_LISTA_FILMES;
END;
//

DELIMITER ;