-- Filmes e os Atores que participaram neles
SELECT
    F.TITULO AS TITULO_FILME,
    A.NOME_ATOR
FROM
    FILME F
JOIN
    FILME_ATOR FA ON F.ID_FILME = FA.ID_FILME
JOIN
    ATOR A ON FA.ID_ATOR = A.ID_ATOR
ORDER BY
    F.TITULO, A.NOME_ATOR;

-- Cinemas e seus respectivos Grupos de Cinema
SELECT
    C.NOME_FANTASIA_CINEMA,
    GC.NOME_GRUPO
FROM
    CINEMA C
JOIN
    GRUPO_CINEMA GC ON C.ID_GRUPO = GC.ID_GRUPO
ORDER BY
    GC.NOME_GRUPO, C.NOME_FANTASIA_CINEMA;

-- Sessões com o Título do Filme correspondente
SELECT
    S.ID_SESSAO,
    S.HORARIO_INICIO,
    S.HORARIO_TERMINO,
    F.TITULO AS TITULO_FILME
FROM
    SESSAO S
JOIN
    FILME F ON S.ID_FILME = F.ID_FILME
ORDER BY
    S.HORARIO_INICIO;

-- Ingressos e o nome do Cliente que os comprou
SELECT
    I.ID_INGRESSO,
    I.PRECO_FINAL,
    I.STATUS_INGRESSO,
    C.NOME_CLIENTE AS CLIENTE_COMPRADOR
FROM
    INGRESSO I
JOIN
    CLIENTE C ON I.ID_CLIENTE = C.ID_CLIENTE
ORDER BY
    I.ID_INGRESSO;