CREATE DATABASE CINESIMBIOSE;

USE CINESIMBIOSE;

CREATE TABLE DISTRIBUIDORA (
    ID_DISTRIBUIDORA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_DISTRIBUIDORA VARCHAR(100) NOT NULL,
    TELEFONE_CONTATO VARCHAR(20),
    EMAIL_CONTATO VARCHAR(100),
    ENDERECO VARCHAR(255)
);

CREATE TABLE GRUPO_CINEMA (
    ID_GRUPO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_GRUPO VARCHAR(100) NOT NULL,
    CONTATO_GRUPO VARCHAR(100)
);

CREATE TABLE CINEMA (
    ID_CINEMA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FANTASIA_CINEMA VARCHAR(100) NOT NULL,
    ENDERECO_CINEMA VARCHAR(255),
    ID_GRUPO INT NOT NULL,
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO_CINEMA(ID_GRUPO)
);

CREATE TABLE CINEMA_DISTRIBUIDORA (
    ID_CINEMA INT,
    ID_DISTRIBUIDORA INT,
    PRIMARY KEY (ID_CINEMA, ID_DISTRIBUIDORA),
    FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(ID_CINEMA),
    FOREIGN KEY (ID_DISTRIBUIDORA) REFERENCES DISTRIBUIDORA(ID_DISTRIBUIDORA)
);

CREATE TABLE SALA (
    ID_SALA INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_SALA VARCHAR(20) NOT NULL,
    CAPACIDADE INT NOT NULL,
    ID_CINEMA INT NOT NULL,
    FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(ID_CINEMA)
);

CREATE TABLE FILME (
    ID_FILME INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    DURACAO_MINUTOS INT,
    CLASSIFICACAO_INDICATIVA VARCHAR(10),
    IDIOMA_ORIGINAL VARCHAR(50),
    IDIOMA_DUBLADO VARCHAR(50),
    GENERO VARCHAR(100)
);

CREATE TABLE ATOR (
    ID_ATOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME_ATOR VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    NACIONALIDADE VARCHAR(50)
);

CREATE TABLE FILME_ATOR (
    ID_FILME INT,
    ID_ATOR INT,
    PRIMARY KEY (ID_FILME, ID_ATOR),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME),
    FOREIGN KEY (ID_ATOR) REFERENCES ATOR(ID_ATOR)
);

CREATE TABLE SESSAO (
    ID_SESSAO INT PRIMARY KEY AUTO_INCREMENT,
    HORARIO_INICIO DATETIME NOT NULL,
    HORARIO_TERMINO DATETIME NOT NULL,
    VALOR_INGRESSO DECIMAL(10, 2) NOT NULL,
    IDIOMA_EXIBICAO VARCHAR(50),
    TIPO_EXIBICAO VARCHAR(50),
    ID_FILME INT NOT NULL,
    ID_SALA INT NOT NULL,
    STATUS_SESSAO VARCHAR(20) DEFAULT 'AGENDADA', -- Nova coluna adicionada
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME),
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA)
);

CREATE TABLE POLTRONA (
    ID_POLTRONA INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_POLTRONA VARCHAR(10) NOT NULL,
    TIPO_POLTRONA VARCHAR(20),
    ID_SALA INT NOT NULL,
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA),
    UNIQUE (NUMERO_POLTRONA, ID_SALA)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    EMAIL_CLIENTE VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE INGRESSO (
    ID_INGRESSO INT PRIMARY KEY AUTO_INCREMENT,
    PRECO_FINAL DECIMAL(10, 2) NOT NULL,
    STATUS_INGRESSO VARCHAR(20) NOT NULL,
    TIPO_INGRESSO VARCHAR(20) NOT NULL,
    ID_SESSAO INT NOT NULL,
    ID_POLTRONA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID_SESSAO),
    FOREIGN KEY (ID_POLTRONA) REFERENCES POLTRONA(ID_POLTRONA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    UNIQUE (ID_SESSAO, ID_POLTRONA)
);

-- Tabela para o log de vendas
CREATE TABLE LOG_VENDAS_INGRESSOS (
    ID_LOG INT PRIMARY KEY AUTO_INCREMENT,
    ID_INGRESSO INT NOT NULL,
    PRECO_VENDA DECIMAL(10, 2) NOT NULL,
    DATA_HORA_VENDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_SESSAO INT,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_INGRESSO) REFERENCES INGRESSO(ID_INGRESSO),
    FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID_SESSAO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

INSERT INTO DISTRIBUIDORA (NOME_DISTRIBUIDORA, TELEFONE_CONTATO, EMAIL_CONTATO, ENDERECO) VALUES
('CINESIMBIOSE', 'XX-XXXX-XXXX', 'contato@cinesimbiose.com.br', 'Rua da Distribuição, 100, Cidade Global'),
('FILMES FANTASTICOS', '55-11-98765-4321', 'contato@filmesfantasticos.com', 'Av. Cinema, 500, SAO PAULO');

INSERT INTO GRUPO_CINEMA (NOME_GRUPO, CONTATO_GRUPO) VALUES
('REDE ESTELAR', 'redestelar@contato.com.br'),
('CINEMAS POP', 'cinemaspop@contato.com.br');

INSERT INTO CLIENTE (NOME_CLIENTE, EMAIL_CLIENTE) VALUES
('MARIA SILVA', 'maria.silva@email.com'),
('JOAO SOUZA', 'joao.souza@email.com'),
('ANA PAULA', 'ana.paula@email.com');

INSERT INTO FILME (TITULO, DESCRICAO, DURACAO_MINUTOS, CLASSIFICACAO_INDICATIVA, IDIOMA_ORIGINAL, IDIOMA_DUBLADO, GENERO) VALUES
('A JORNADA DO HEROI', 'UMA EPICA AVENTURA SOBRE UM JOVEM EM BUSCA DE SUA ORIGEM.', 180, 'LIVRE', 'INGLES', 'PORTUGUES', 'AVENTURA'),
('O MISTERIO DA ILHA', 'UM SUSPENSE INTRIGANTE QUE SE PASSA EM UMA ILHA ISOLADA.', 110, '14 ANOS', 'PORTUGUES', NULL, 'SUSPENSE'),
('COMEDIA ROMANTICA PERFEITA', 'UM FILME LEVE E DIVERTIDO SOBRE AMOR E AMIZADE.', 95, '12 ANOS', 'INGLES', 'PORTUGUES', 'COMEDIA ROMANTICA'),
('DOCUMENTARIO DA NATUREZA', 'EXPLORE A VIDA SELVAGEM EM SEUS HABITATS NATURAIS.', 60, 'LIVRE', 'PORTUGUES', 'INGLES', 'DOCUMENTARIO');

INSERT INTO ATOR (NOME_ATOR, DATA_NASCIMENTO, NACIONALIDADE) VALUES
('PEDRO ALVARES', '1980-03-10', 'BRASILEIRA'),
('SOFIA COSTA', '1992-07-25', 'PORTUGUESA'),
('LUCAS FERNANDES', '1975-11-01', 'BRASILEIRA'),
('ISABELA LIMA', '1995-01-18', 'AMERICANA');

INSERT INTO CINEMA (NOME_FANTASIA_CINEMA, ENDERECO_CINEMA, ID_GRUPO) VALUES
('CINE ESTRELA SUL', 'RUA DAS PALMEIRAS, 100, BAIRRO JARDIM', 1),
('MEGA CINE CENTRO', 'AV. PRINCIPAL, 50, CENTRO', 1),
('CINE KIDS MANIA', 'SHOPPING DA CRIANCA, LOJA 10, CIDADE NOVA', 2);

INSERT INTO CINEMA_DISTRIBUIDORA (ID_CINEMA, ID_DISTRIBUIDORA) VALUES
(1, 1),
(1, 2),
(2, 1),
(3, 2);

INSERT INTO SALA (NUMERO_SALA, CAPACIDADE, ID_CINEMA) VALUES
('SALA 1', 150, 1),
('SALA VIP', 50, 1),
('SALA MASTER', 200, 2),
('SALA INFANTIL', 80, 3);

INSERT INTO FILME_ATOR (ID_FILME, ID_ATOR) VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 1),
(3, 4);

INSERT INTO SESSAO (HORARIO_INICIO, HORARIO_TERMINO, VALOR_INGRESSO, IDIOMA_EXIBICAO, TIPO_EXIBICAO, ID_FILME, ID_SALA, STATUS_SESSAO) VALUES
('2025-06-25 10:00:00', '2025-06-25 13:00:00', 35.00, 'PORTUGUES', '3D', 1, 1, 'ENCERRADA'), -- Exemplo de sessão já encerrada
('2025-06-25 14:00:00', '2025-06-25 15:50:00', 30.00, 'PORTUGUES', '2D', 2, 1, 'AGENDADA'),
('2025-06-25 19:30:00', '2025-06-25 21:05:00', 40.00, 'INGLES', 'IMAX', 3, 2, 'AGENDADA'),
('2025-06-26 10:30:00', '2025-06-26 11:30:00', 25.00, 'PORTUGUES', '2D', 4, 4, 'AGENDADA');

INSERT INTO POLTRONA (NUMERO_POLTRONA, TIPO_POLTRONA, ID_SALA) VALUES
('A1', 'NORMAL', 1), ('A2', 'NORMAL', 1), ('A3', 'NORMAL', 1),
('B1', 'NORMAL', 1), ('B2', 'NORMAL', 1), ('B3', 'NORMAL', 1),
('C1', 'NORMAL', 1),
('V1', 'VIP', 2), ('V2', 'VIP', 2), ('V3', 'VIP', 2),
('M1', 'NORMAL', 3), ('M2', 'NORMAL', 3);

INSERT INTO INGRESSO (PRECO_FINAL, STATUS_INGRESSO, TIPO_INGRESSO, ID_SESSAO, ID_POLTRONA, ID_CLIENTE) VALUES
(35.00, 'VENDIDO', 'INTEIRA', 1, 1, 1),
(20.00, 'VENDIDO', 'MEIA-ENTRADA', 3, 8, 2),
(35.00, 'RESERVADO', 'INTEIRA', 1, 2, 3);
